OPENAI_API_KEY = "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"
OPENAI_ORG = "org-yUl6CfQGDoZuViS7eDezZual"
OPENAI_PROJECT = "proj_ZZF0OIytwcKOYc8yvFusq8Nd"